name: GitHub Classroom Workflow

on:
  push:
    branches: [main]

jobs:
  # separate job so status of autograder affects status of job
  # without having to use continue-on-error and allowing concurrent followup jobs
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      homework_name: ${{ steps.setup-homework.output.homework_name }}
      points: ${{ steps.autograder.outputs.points }}
      outcome: ${{ steps.autograder.outcome }}

    steps:
      # the autograder action does not have access to environment variables
      # the setup action hard-codes those values where needed
      - name: Setup Homework Test Environment
        id: setup-homework
        uses: usf-cs272-spring2022/action-homework-setup@main

      # autograder stops commands while running
      - name: Run Autograder
        id: autograder
        uses: education/autograding@v1

  badge:
    name: Generate Points Badge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs: grade

    steps:
      - name: Output Result
        uses: usf-cs272-spring2022/action-homework-badge@main
        with:
          outcome: ${{ needs.grade.outputs.outcome }}
          points: ${{ needs.grade.outputs.points }}
